package com.javaspring.team2.project.smdb.domain;

public enum Genre {
    ACTION, ADVENTURE, BIOGRAPHY, COMEDY,
    DRAMA, FANTASY, SCIFI, HORROR, ROMANCE,
    THRILLER, MYSTERY, CRIME, ANIMATION, SUPERHERO,
    WESTERN, MUSIC, HISTORY, DOCUMENTARY, SHORTFILM
}
